# This is a basic workflow to help you get started with Actions

name: CREATEPACKAGEONRELEASE

# Controls when the action will run. 
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Init_Log
        run: echo CREATEPACKAGEONRELEASE Started!

      # Runs a set of commands using the runners shell
      - name: Context_Log
        run: |
          echo "Release: $GITHUB_REF"
